org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.2.9
forge_version_range=[40,)
loader_version_range=[40,)

mapping_channel=parchment
mapping_version=2022.11.06

mod_id=vh_client_optimize
mod_name=VHClientOptimize
mod_version=1.0.4-u19
mod_group_id=me.justahuman
mod_authors=JustAHuman
mod_license=GNU GPL 3.0
mod_description=A client optimization mod for Vaulthunters.

vaulthunters_version=6833423
curios_version=4418032
create_version=5797603
spark_version=4505375
powah_version=4183076
jei_version=4351311
jeitweaker_version=3950183
ctm_version=3933537
selene_version=4747959